version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - echo "Nothing to build here as it's node!"    
  post_build:
    commands:
     # - pip3 uninstall -y awscli
      #- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #- unzip awscliv2.zip
      #- ./aws/install
      #- aws --version
      #- aws cloudformation package --template-file template.yaml 
      #                                  --s3-bucket codepipeline-us-west-1-788309214524
      #                                  --output-template-file output.yaml
      #                                 --region us-west-1
   
artifacts:
  type: zip
  files:
    - template.yaml
    - output.yaml
